version: '3.8'

# Конфигурация ТОЛЬКО для фронтенда
# Бэкенд должен быть запущен отдельно на том же сервере

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: smiio_frontend
    restart: always
    environment:
      # Используем имя контейнера бэкенда (trading_app_prod)
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://trading_app_prod:8000}
      NODE_ENV: production
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    networks:
      - trading_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  trading_network:
    external: true
    name: trading_system_trading_network

