version: '3.8'

# Конфигурация ТОЛЬКО для фронтенда
# Бэкенд должен быть запущен отдельно на том же сервере

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: smiio_frontend
    restart: always
    network_mode: "host"
    environment:
      # Используем localhost так как network_mode: host
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8000}
      NODE_ENV: production
      PORT: ${FRONTEND_PORT:-3000}
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

